services:
  monitoring:
    image: nicolargo/glances:latest-full
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=1026
      - PGID=1026
      - TZ=Etc/UTC
      - "GLANCES_OPT=-w"
