---
services:
  radarr:
    image: linuxserver/radarr:latest
    network_mode: "host"
    container_name: radar
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /volume1/docker/configs/radarr:/config
      - /volume2/Video:/video
    ports:
      - 7878:7878
    restart: unless-stopped
